import { useTonConnectUI } from '@tonconnect/ui-react';
import { useEffect, useState } from 'react';

function App() {
  const [tonConnectUI] = useTonConnectUI();
    const [connected, setConnected] = useState(false);
      const [balance, setBalance] = useState(0.124);

        useEffect(() => {
            tonConnectUI.onStatusChange((wallet) => {
                  if (wallet) setConnected(true);
                      });
                        }, [tonConnectUI]);

                          return (
                              <div style={{
                                    padding: '20px',
                                          textAlign: 'center',
                                                background: 'linear-gradient(#e8f5e9, #c8e6c9)',
                                                      minHeight: '100vh',
                                                            fontFamily: 'system-ui',
                                                                  color: '#2e7d32'
                                                                      }}>
                                                                            <h1 style={{ margin: '0 0 10px 0', fontSize: '28px' }}>🌾 Harvestia</h1>
                                                                                  <p style={{ fontSize: '18px', marginBottom: '20px' }}>Farm Real TON</p>

                                                                                        <div style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '30px' }}>
                                                                                                💰 {balance} TON
                                                                                                      </div>

                                                                                                            {!connected ? (
                                                                                                                    <button 
                                                                                                                              onClick={() => tonConnectUI.openModal()}
                                                                                                                                        style={{
                                                                                                                                                    padding: '16px 32px',
                                                                                                                                                                fontSize: '18px',
                                                                                                                                                                            background: '#00b140',
                                                                                                                                                                                        color: 'white',
                                                                                                                                                                                                    border: 'none',
                                                                                                                                                                                                                borderRadius: '12px',
                                                                                                                                                                                                                            width: '100%',
                                                                                                                                                                                                                                        marginBottom: '30px'
                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                    💰 Connect TON Wallet
                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                    <h2 style={{ marginBottom: '15px' }}>🏡 Farm Kamu</h2>
                                                                                                                                                                                                                                                                                                              <div style={{ 
                                                                                                                                                                                                                                                                                                                          display: 'grid', 
                                                                                                                                                                                                                                                                                                                                      gridTemplateColumns: '1fr 1fr 1fr', 
                                                                                                                                                                                                                                                                                                                                                  gap: '12px', 
                                                                                                                                                                                                                                                                                                                                                              marginBottom: '30px' 
                                                                                                                                                                                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ background: 'white', padding: '15px', borderRadius: '12px' }}>🌱 Gandum</div>
                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ background: 'white', padding: '15px', borderRadius: '12px' }}>🌽 Jagung</div>
                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ background: 'white', padding: '15px', borderRadius: '12px' }}>🐮 Sapi</div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: '18px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: '20px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: '#4ade80',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: '15px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🌾 Panen & Jual → +0.035 TON
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: '16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: '#f59e0b',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: '100%'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  🛒 Shop Bibit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;